### ISSUE TITLE
Stop the Program when the options_press

### ISSUE THREAD

**Issue by jello261** [ArturSpirin/pyPS4Controller#11]
So I'm using Tkinter as the main GUI to control a robot, and I have a button to connect the controller to use that but I want to add in an option to allow me to press the options button and stop the listening function. Is there any way to do this.

**Comment by ArturSpirin** [comment]
@jello261 Yes, a Controller object has an attribute "stop" which you can set to True/False.
If you set it to True, the listening event loop will exit.

```py
constoller.stop = True
```

**Comment by ArturSpirin** [comment]
There was a bug in version < 1.2.0 - Fix was just published so make sure you download the latest via pip, you want 1.2.1

**Comment by jello261** [comment]
Sorry im new to python so this is what I would have to do?
`def on_share_press(self):
            Controller.stop = True`

**Comment by ArturSpirin** [comment]
@jello261 Close. You want to make sure that you pass the object for the controller that you created.
For example
```py
mycontroller = MyController(interface="/dev/input/js0")
mycontroller.listen()
```
mycontroller is the object you created. In order to stop listening for events on that controller
```py
def on_share_press(self): 
    mycontroller.stop = True
```

You can think about how you want to make the controller object accessible to the button hook. You can either make is static or create a custom event definition and store that object inside.
