### ISSUE TITLE
Cannot run any subsequent lines of code after Controller.listen()

### ISSUE THREAD

**Issue by jatinvinkumar** [ArturSpirin/pyPS4Controller#2]
Hi Artur, 

Thank you for posting an amazing repository! It seems _file.read(Controller.EVENT_SIZE) in read_events() Controller.py makes the program wait until an event is triggered. Could you please advise me on how I can get code to execute when no events or no buttons are being pressed? Once again thank you so much for your time and effort in providing us this awesome repo!

**Comment by ArturSpirin** [comment]
Hi @jatinvinkumar Events are triggering on update of /dev/input/js0 or another interface that was specified. If it seems like the program is waiting, its because there is nothing new which matches any of the known button event mapping is coming in on the interface that we are listening.

If you can provide me more context on what you are trying to do, I might be able to provide a suggestion.

**Comment by jatinvinkumar** [comment]
Hi @ArturSpirin, I'm using the PS4 to control steering for a robot car project. One of the requirements is to capture footage from an onboard camera and associate each frame to the current steering angle. 

My initial logic was to capture the frame inside listen()'s while loop and give it a default 'straight' angle which would equate to no events being triggered. If the L3 stick was moved right or left then I would associate the moved angle instead. Please let me know what your thoughts on this are. Thank you for your time.

**Comment by ArturSpirin** [comment]
@jatinvinkumar I suggest to create a class/db/file that will be used to keep the state. Class is better because in the case of L3, there will be a lot of events and you will definitely notice latency if you use anything IO. You will want to define the following events in your controller:
```
on_L3_up
on_L3_down
on_L3_left
on_L3_right
on_L3_at_rest  # L3 joystick is at rest after the joystick was moved and let go off
on_L3_press  # L3 joystick is clicked. This event is only detected when connecting without ds4drv
on_L3_release  # L3 joystick is released after the click. This event is only detected when connecting without ds4drv
```
and update the state with your desired information when any of those events are triggered.
