### ISSUE TITLE
Button has to be pushed twice to release.

### ISSUE THREAD

**Issue by ghost** [ArturSpirin/pyPS4Controller#5]
Ubuntu 20.04, Python 3.8.2, PS4 DualShock.

When I loaded up the test script when I press X, Circle, Square, Triangle, D-Pad, L1, L2 etc script will indicate the button has been pressed. In order to release the button you have to press it a second time. 

on_square_press   <--- button pressed first time
on_square_release  <---button pressed second time
on_square_press    <--- button pressed first time
on_square_release <---button pressed second time

Also appears the triggers and joypads are less sensitive and trigger does not fully decompress all the way when quickly released... 

Tested the script on a  Raspberry Pi 4 running Raspian and did not have any these issues.
Tested it another computer runnning ubuntu 20.04 had same  issues.      
Ran jstest-gtk everything appeared to be work correctly.

**Comment by sheeshee** [comment]
Hi,

I encountered a similar issue. I don't know if the root cause is the same, but I managed to fix it in the end by cloning this repo and changing the "event packet format" from `LhBB` to `3Bh2b` like [so](https://github.com/sheeshee/pyPS4Controller/commit/d65ee35a629703c55e4b62a187975791d788976d#diff-32ea5eed5b3b77b27a2e0613e5cf24c2L427-R428).

Seems to work just fine now!

I am on Linux Mint 19.1 Cinnamon 4.0.10, Python 3.8.1.

**Comment by ArturSpirin** [comment]
This is great info @sheeshee . Thank you very much!

**Comment by ArturSpirin** [comment]
Thanks @sheeshee for helping to address this issue!

**Comment by iobotic-code** [comment]
Hello guys, I really don't know how to mapping the buttons, could you help me?

Also, I would like to run more code if I can't find any control to connect but once the control isn't found it the program ends!

Thanks very much
